#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Symfony\Component\DependencyInjection\ContainerBuilder;

/** @var ContainerBuilder $container */
$container = require_once __DIR__ . '/config/services.php';

$application = new Application();

$consoleCommands = $container->findTaggedServiceIds('console.command');
foreach ($consoleCommands as $consoleCommand => $tags) {
    $application->add($container->get($consoleCommand));
}
$application->setDefaultCommand('pwned', true);

$application->run();
